name: Update db

on:
  push:
    branches:
    - main
    patch:
    - '.github/workflows/update-db.yml'
    - 'main.sh'
  pull_request:
    patch:
    - '.github/workflows/update-db.yml'
    - 'main.sh'
  schedule:
  - cron:  '0,30 0-23 * * *'

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update-db:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target_repo: [main__aarch64,
                      main__arm,
                      main__i686,
                      main__x86_64,
                      x11__aarch64,
                      x11__arm,
                      x11__i686,
                      x11__x86_64,
                      root__aarch64,
                      root__arm,
                      root__i686,
                      root__x86_64,
                      tur__aarch64,
                      tur__arm,
                      tur__i686,
                      tur__x86_64,
                      tur-continuous__aarch64,
                      tur-continuous__arm,
                      tur-continuous__i686,
                      tur-continuous__x86_64,
                      tur-multilib__aarch64,
                      tur-multilib__arm,
                      tur-multilib__i686,
                      tur-multilib__x86_64,
                      gpkg__aarch64,
                      gpkg__arm,
                      gpkg__x86_64,
                      gpkg__i686,
                      cgct__x86_64]
      fail-fast: false
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set pacman tool for db
      uses: termux-pacman/pacman-actions@v2.5
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Import gpg key
      run: |
        mkdir gk
        echo "${{ secrets.SF_GPG }}" > gk/termux-pacman.gpg
        gpg --pinentry-mode=loopback --passphrase '${{ secrets.PW_GPG }}' --import gk/termux-pacman.gpg
        echo "${{ secrets.SF_GPG_BOT }}" > gk/termux-pacman-bot.gpg
        gpg --pinentry-mode=loopback --passphrase '${{ secrets.PW_GPG_BOT }}' --import gk/termux-pacman-bot.gpg
        rm -fr gk
    - name: Update db
      id: update-db
      env:
        KEY_GPG: ${{ secrets.KEY_GPG }}
        PW_GPG: ${{ secrets.PW_GPG }}
        SFPU: ${{ secrets.SFPU }}
        TARGET_REPO: ${{ matrix.target_repo }}
        GITHUB_EVENT: ${{ github.event_name }}
      run: |
        if [[ "${GITHUB_EVENT}" = "schedule" && "${{ github.ref_name }}" != "main" ]]; then
          echo "stop schedule outside main branch"
          exit 1
        fi
        export UPDATE_RSYNC=false
        source ./main.sh "${TARGET_REPO%%__*}" "${TARGET_REPO#*__}"
        echo "UPDATE_RSYNC_${TARGET_REPO}=${UPDATE_RSYNC}" >> "$GITHUB_OUTPUT"
    outputs:
      update_rsync_main__aarch64: ${{ steps.update-db.outputs.UPDATE_RSYNC_main__aarch64 }}
      update_rsync_main__arm: ${{ steps.update-db.outputs.UPDATE_RSYNC_main__arm }}
      update_rsync_main__i686: ${{ steps.update-db.outputs.UPDATE_RSYNC_main__i686 }}
      update_rsync_main__x86_64: ${{ steps.update-db.outputs.UPDATE_RSYNC_main__x86_64 }}
      update_rsync_x11__aarch64: ${{ steps.update-db.outputs.UPDATE_RSYNC_x11__aarch64 }}
      update_rsync_x11__arm: ${{ steps.update-db.outputs.UPDATE_RSYNC_x11__arm }}
      update_rsync_x11__i686: ${{ steps.update-db.outputs.UPDATE_RSYNC_x11__i686 }}
      update_rsync_x11__x86_64: ${{ steps.update-db.outputs.UPDATE_RSYNC_x11__x86_64 }}
      update_rsync_root__aarch64: ${{ steps.update-db.outputs.UPDATE_RSYNC_root__aarch64 }}
      update_rsync_root__arm: ${{ steps.update-db.outputs.UPDATE_RSYNC_root__arm }}
      update_rsync_root__i686: ${{ steps.update-db.outputs.UPDATE_RSYNC_root__i686 }}
      update_rsync_root__x86_64: ${{ steps.update-db.outputs.UPDATE_RSYNC_root__x86_64 }}
      update_rsync_tur__aarch64: ${{ steps.update-db.outputs.UPDATE_RSYNC_tur__aarch64 }}
      update_rsync_tur__arm: ${{ steps.update-db.outputs.UPDATE_RSYNC_tur__arm }}
      update_rsync_tur__i686: ${{ steps.update-db.outputs.UPDATE_RSYNC_tur__i686 }}
      update_rsync_tur__x86_64: ${{ steps.update-db.outputs.UPDATE_RSYNC_tur__x86_64 }}
      update_rsync_tur-continuous__aarch64: ${{ steps.update-db.outputs.UPDATE_RSYNC_tur-continuous__aarch64 }}
      update_rsync_tur-continuous__arm: ${{ steps.update-db.outputs.UPDATE_RSYNC_tur-continuous__arm }}
      update_rsync_tur-continuous__i686: ${{ steps.update-db.outputs.UPDATE_RSYNC_tur-continuous__i686 }}
      update_rsync_tur-continuous__x86_64: ${{ steps.update-db.outputs.UPDATE_RSYNC_tur-continuous__x86_64 }}
      update_rsync_tur-multilib__aarch64: ${{ steps.update-db.outputs.UPDATE_RSYNC_tur-multilib__aarch64 }}
      update_rsync_tur-multilib__arm: ${{ steps.update-db.outputs.UPDATE_RSYNC_tur-multilib__arm }}
      update_rsync_tur-multilib__i686: ${{ steps.update-db.outputs.UPDATE_RSYNC_tur-multilib__i686 }}
      update_rsync_tur-multilib__x86_64: ${{ steps.update-db.outputs.UPDATE_RSYNC_tur-multilib__x86_64 }}
      update_rsync_gpkg__aarch64: ${{ steps.update-db.outputs.UPDATE_RSYNC_gpkg__aarch64 }}
      update_rsync_gpkg__arm: ${{ steps.update-db.outputs.UPDATE_RSYNC_gpkg__arm }}
      update_rsync_gpkg__x86_64: ${{ steps.update-db.outputs.UPDATE_RSYNC_gpkg__x86_64 }}
      update_rsync_gpkg__i686: ${{ steps.update-db.outputs.UPDATE_RSYNC_gpkg__i686 }}
      update_rsync_cgct__x86_64: ${{ steps.update-db.outputs.UPDATE_RSYNC_cgct__x86_64 }}
  update-rsync:
    runs-on: ubuntu-24.04
    needs: update-db
    steps:
    - name: Import crt
      run: |
        echo "${{ secrets.UR_SERVER_CRT }}" > ./server.crt
        echo "${{ secrets.UR_CLIENT_CRT }}" > ./client.crt
    - name: Update rsync
      env:
        UPDATE_RSYNC: ${{ toJSON(needs.update-db.outputs) }}
        GITHUB_EVENT: ${{ github.event_name }}
      run: |
        if jq -r '.[]' <<< "${UPDATE_RSYNC}" | grep -q '^true$'; then
          if [ "${GITHUB_EVENT}" = "pull_request" ]; then
            echo "Variables have successfully triggered the rsync update algorithm, testing complete"
          else
            for i in {1..5}; do
              res=$(curl -s -X POST -H "${{ secrets.UR_HEADERS }}" --cacert ./server.crt --cert ./client.crt "${{ secrets.UR_ADDRESS }}" | sed 's/\r//g')
              echo "Result: ${res}"
              if [ "${res}" = "ok" ]; then
                echo "Success"
                break
              elif [ "${res}" = "busy" ]; then
                if [ "${i}" = "5" ]; then
                  echo "The 5 time is busy, looks like something is broken"
                  exit 1
                fi
                echo "The system is busy, waiting 70 seconds ${i} times"
                sleep 70
                continue
              else
                echo "Internal error occurred"
                exit 1
              fi
            done
          fi
        else
          echo "Nothing to do"
        fi
